[workspace]
members = ["projects/*"]
default-members = [
    "projects/waifu2x",
]
exclude = [
    "projects/.DS_Store",
    "projects/waifu2x-models",
]

[profile.release]
lto = true
panic = "abort"
